USE RESTAURANTE
GO

--/
SELECT * FROM CONTATOS
GO

ALTER TABLE CONTATOS
ADD CONSTRAINT UQ_EMAIL
UNIQUE (EMAIL)
GO 

ALTER TABLE CONTATOS
ADD CONSTRAINT UQ_CELULAR
UNIQUE (CELULAR)
GO

ALTER TABLE CONTATOS
ADD ID_CLIENTE INT NULL
GO

ALTER TABLE CONTATOS
ADD CONSTRAINT FK_CONTATOS_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE
GO

SP_HELP CONTATOS 
GO
--\----------------------------------------------------------------------

--/
SELECT * FROM CLIENTE GO

ALTER TABLE CLIENTE
ADD CONSTRAINT UQ_CONTATOS_CPF
UNIQUE (CPF)
GO

SP_HELP CLIENTE 
GO
--\----------------------------------------------------------------------


--/
SELECT * FROM FUNCIONARIOS GO

ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT UQ_FUNCIONARIO_CPF
UNIQUE (CPF)
GO

ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT CK_FUNCIONARIOS_CARGO
CHECK (CARGO IN ('ATENTENDE','GARÇOM','COZINHEIRO'))
GO

ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT DF_FUNCIONARIOS_ATIVO
DEFAULT 1 FOR ATIVO
GO

SP_HELP FUNCIONARIOS;
--\----------------------------------------------------------------------

--/

SELECT * FROM AGENDA GO

ALTER TABLE AGENDA
ADD ID_FUNCIONARIO INT,
ID_CLIENTE INT
GO

ALTER TABLE AGENDA
ADD CONSTRAINT FK_AGENDA_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIOS(IDFUNCIONARIO)
ON DELETE CASCADE
GO

ALTER TABLE AGENDA
ADD CONSTRAINT FK_AGENDA_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE
GO


SP_HELP AGENDA
--\----------------------------------------------------------------------

--/
SELECT * FROM MESA GO

ALTER TABLE MESA
ADD CONSTRAINT DF_MESA_ENTRADA
DEFAULT GETDATE() FOR ENTRADA
GO

ALTER TABLE MESA
ADD ID_CLIENTE INT;

ALTER TABLE MESA
ADD CONSTRAINT FK_MESA_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)
ON DELETE CASCADE
GO

SP_HELP MESA GO

--\-------------------------------------------------------------------

ALTER TABLE CARDAPIO
ADD CONSTRAINT CK_CARDAPIO_TIPO
CHECK(TIPO IN ('BEBIDAS', 'LANCHES','SOBREMESAS','VEGANOS','ALCOÓLICOS','EXECUTIVOS'))
GO


--/
SELECT * FROM PEDIDOS GO

ALTER TABLE PEDIDOS
ADD ID_MESA INT,
	ID_FUNCIONARIO INT,
	ID_CARDAPIO INT
GO

ALTER TABLE PEDIDOS
ADD CONSTRAINT DF_PEDIDOS_HORARIO
DEFAULT GETDATE() FOR HORARIO
GO

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_MESA
FOREIGN KEY (ID_MESA)
REFERENCES MESA(IDMESA)
ON DELETE CASCADE
GO


ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIOS(IDFUNCIONARIO)
ON DELETE CASCADE
GO


ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_CARDAPIO
FOREIGN KEY (ID_CARDAPIO)
REFERENCES CARDAPIO(IDCARDAPIO)
ON DELETE CASCADE
GO
--\-------------------------------------------------------------------



SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE GO
