-- ORDEM DE EXECUÇÃO

-- AGENDANDO CLIENTES ---INICIO--------------------------------------------------------------------------

SELECT * FROM VW_CLIENTES
GO
SELECT * FROM VW_AGENDAMENTO
GO

EXEC SP_AGENDA_CLIENTE 'N','10000000001','00000000020','BARRY ALEN','BERRY@EMAIL.COM','11900001001',NULL,'09-11-2020 13:58',2;
--COM CLIENTE CADASTRANDO.
GO

EXEC SP_AGENDA_CLIENTE 'S','10000000001','00000000030','BRUCE WAYNE','BRUCE@EMAIL.COM','11900001002',NULL,'09-11-2020 15:41',1;
--COM CLIENTE CADASTRANDO 2.
GO

SELECT * FROM VW_AGENDAMENTO WHERE (GETDATE() BETWEEN HORARIO AND TOLERANCIA)

-- AGENDANDO CLIENTES ---FIM-----------------------------------------------------------------------------

-- DIRECIONANDO AGENDA ---INICIO--------------------------------------------------------------------------

SELECT * FROM VW_AGENDAMENTO GO

EXEC SP_DIRECIONA_AGENDA 'S','00000000020','BERRY ALEN';
--DIRECIONANDO AGENDAMENTO PARA MESA
GO

EXEC SP_DIRECIONA_AGENDA 'N','00000000030','BRUCE WAYNE';
--DIRECIONANDO AGENDAMENTO PARA FILA
GO

SELECT * FROM VW_AGENDAMENTO 
WHERE (GETDATE() BETWEEN HORARIO AND TOLERANCIA)
ORDER BY HORARIO

SELECT * FROM ##FILA GO
SELECT *FROM VW_MESA GO

-- DIRECIONANDO AGENDA ---FIM--------------------------------------------------------------------------

-- GERENCIA FILA ---INICIO-----------------------------------------------------------------------------
SELECT * FROM ##FILA GO

EXEC SP_GERENCIA_FILA 4
-- GERENCIANDO A FILA
GO

SELECT * FROM VW_MESA GO
-- GERENCIA FILA ---FIM-----------------------------------------------------------------------------

-- ANOTA PEDIDO ---INICIO---------------------------------------------------------------------------
EXEC SP_ANOTA_PEDIDO 'Virada Paulista','SEM CEBOLA','10000000001', 1
GO

INSERT INTO PEDIDOS(HORARIO,OBS,ID_MESA,ID_FUNCIONARIO,ID_CARDAPIO)
VALUES(GETDATE(),'SEM CEBOLA',1,1,3)

select * from PEDIDOS

SELECT * FROM VW_PEDIDOS -- ERRO
SELECT * FROM PEDIDOS
SELECT * FROM ##LISTA

delete from PEDIDOS


-- ANOTA PEDIDO ---FIM------------------------------------------------------------------------------

SELECT * FROM FUNCIONARIOS
SELECT * FROM MESA
SELECT * FROM CARDAPIO




