-- INSERT CLIENTES E CONTATOS

SELECT * FROM CLIENTE

INSERT INTO CLIENTE VALUES('FULANO DE TAL2','00000000001');
INSERT INTO CONTATOS(EMAIL,CELULAR,ID_CLIENTE) VALUES('FULANO2@EMAIL.COM','11900000002',1);

SELECT * FROM CLIENTE GO

UPDATE CONTATOS 
SET TELEFONE = 'VAZIO'
WHERE IDCONTATO = 1
GO

-- INSERT FUNCIONÁRIOS.

INSERT INTO FUNCIONARIOS VALUES ('ALFRED', '10000000001','20-12-2000','GARÇOM',DEFAULT);

SELECT * FROM FUNCIONARIOS
GO

-- INSERT AGENDA.

INSERT INTO AGENDA(LUGARES,HORARIO,ID_FUNCIONARIO,ID_CLIENTE) VALUES(3,'21-10-2020 20:00',1,1);

SELECT * FROM AGENDA GO

INSERT INTO CARDAPIO(NOME_PRATO,TIPO) 
VALUES ('Virada Paulista','EXECUTIVOS'),
	   ('Parmegiana','EXECUTIVOS'),
	   ('Strogonof', 'EXECUTIVOS'),
	   ('Pudim', 'SOBREMESAS'),
	   ('Mousse de Limão', 'SOBREMESAS'),
	   ('Coca Cola lata', 'BEBIDAS'),
	   ('Guaraná lata', 'BEBIDAS'),
	   ('X Salada', 'LANCHES'),
	   ('X Bacon', 'LANCHES')
GO

