-- Cadastro de Funcionário

USE RESTAURANTE GO

SELECT * FROM FUNCIONARIOS

CREATE PROCEDURE SP_CADASTRO_FUNCIONARIO @NOME_FUNCIONARIO VARCHAR(128), @CPF NVARCHAR(11), 
@NASCIMENTO DATE, @CARGO NVARCHAR(50)

AS
	BEGIN
		DECLARE @ERRO INT

		IF (SELECT COUNT(*) FROM FUNCIONARIOS WHERE CPF = @CPF) >= 1 
			BEGIN
				PRINT 'JÁ EXISTE ALGUÉM COM ESSE CPF.'
				SET @ERRO = 1
			END
		ELSE IF (@CARGO <> 'ATENDENTE') AND (@CARGO <> 'GARÇOM') AND (@CARGO <> 'COZINHEIRO')
			BEGIN
				PRINT 'O CARGO MENCIONADO NÃO EXISTE!'
				SET @ERRO = 1
			END
		ELSE IF (SELECT COUNT(*) FROM FUNCIONARIOS WHERE CPF = @CPF) = 0 
			BEGIN
				INSERT INTO FUNCIONARIOS 
				VALUES(@NOME_FUNCIONARIO,@CPF,@NASCIMENTO,@CARGO,DEFAULT)
				PRINT 'USUARIO CADASTRADO'
			END
		ELSE
			BEGIN
				PRINT 'ERRO DESCONHECIDO.'
			END
	END
GO

EXEC SP_CADASTRO_FUNCIONARIO 'ALFREDO','10000000002','02-05-2000','GARÇOM'

SELECT * FROM FUNCIONARIOS