--DIRECIONANDO O REGISTRO AGENDADO A MESA.

use restaurante

CREATE PROCEDURE SP_DIRECIONA_AGENDA
@TEM_MESA CHAR(3),@CPF_CLIENTE NVARCHAR(11), @NOME NVARCHAR(128) = NULL

AS
	BEGIN TRY
		
		DECLARE @FK_CLIENTE INT 
		DECLARE @CPF NVARCHAR(30)
		DECLARE @ID INT

		SET @CPF = (SELECT TOP(1) CPF FROM VW_AGENDAMENTO WHERE CPF = @CPF_CLIENTE
					AND HORARIO <=GETDATE() AND TOLERANCIA >= GETDATE() ORDER BY HORARIO DESC)
		SET @FK_CLIENTE = (SELECT IDCLIENTE FROM CLIENTE WHERE CPF = @CPF);
		SET @ID = (SELECT TOP(1) IDAGENDA FROM AGENDA WHERE ID_CLIENTE = @FK_CLIENTE
					AND HORARIO <=GETDATE() AND TOLERANCIA >= GETDATE() ORDER BY HORARIO DESC)

		IF  ((@TEM_MESA LIKE 'S%') AND (@FK_CLIENTE IS NOT NULL) AND (@ID IS NOT NULL))
			BEGIN
				INSERT INTO MESA (NUMERO,ENTRADA,ID_CLIENTE) VALUES(1,GETDATE(),@FK_CLIENTE);
				UPDATE AGENDA SET CHEGADA = GETDATE() WHERE IDAGENDA = @ID;
				SELECT TOP(1) * FROM VW_MESA ORDER BY ENTRADA DESC
				PRINT 'MESA LIBERADA!'
			END;
		ELSE IF ((@TEM_MESA LIKE 'N%') AND (@FK_CLIENTE IS NOT NULL) AND (@ID IS NOT NULL))
			BEGIN
				INSERT INTO [dbo].[##FILA] (CHEGADA,CPF,ID_CLIENTE,NOME) 
				VALUES (GETDATE(),@CPF_CLIENTE,@FK_CLIENTE,@NOME);
				UPDATE AGENDA SET CHEGADA = GETDATE() WHERE IDAGENDA = @ID;
				PRINT ' O CLIENTE SERÁ DIRECIONADO A FILA E TERÁ PRIORIDADE.'
			END;
		ELSE IF ((@FK_CLIENTE IS NULL) OR (@FK_CLIENTE = ''))
			BEGIN
				INSERT INTO [dbo].[##FILA] (CHEGADA,CPF,NOME)  VALUES (GETDATE(),@CPF_CLIENTE,@NOME);
				PRINT 'ESSE HORARIO NÃO EXISTE OU NÃO ESTÁ MAIS DISPONIVEL
					   O CLIENTE SERÁ DIRECIONADO A FILA #SEM PRIORIDADE DE AGENDAMENTO.'
			END;
		ELSE
			BEGIN
				SELECT 'NÃO ENTROU EM NENHUM IF'
			END;
	END TRY
	BEGIN CATCH
		SELECT   
        ERROR_NUMBER() AS ErrorNumber  
        ,ERROR_MESSAGE() AS ErrorMessage;  
	END CATCH
GO

SELECT TOP(1) * FROM VW_AGENDAMENTO WHERE CPF = '00000000004' ORDER BY HORARIO 
SELECT * FROM VW_MESA
SELECT * FROM MESA

SELECT * FROM AGENDA
SELECT * FROM VW_AGENDAMENTO

DROP VIEW VW_AGENDAMENTO

SELECT * FROM VW_AGENDAMENTO

EXEC SP_AGENDA_CLIENTE 'S','10000000001','00000000004',NULL,NULL,NULL,NULL,'05-11-2020 20:17',5;
--COM CLIENTE JÁ CADASTRADO.

EXEC SP_DIRECIONA_AGENDA 'S','00000000004','FULANO DE TAL 2';

SELECT * FROM CLIENTE

DROP PROCEDURE SP_DIRECIONA_AGENDA
