-- PROCEDURE PARA GERENCIAR FILA

-- CLIENTES QUE AGENDARAM E FORAM PARA A FILA POR FALTA DE MESA. POSSUEM PRIORIDADE.

CREATE PROCEDURE SP_GERENCIA_FILA @N_MESA INT
AS
	BEGIN
		DECLARE @ID INT
		DECLARE @FK_CLIENTE INT
		
		SET @ID = (SELECT TOP(1) IDFILA  FROM ##FILA WHERE CHAMADA IS NULL AND ID_CLIENTE IS NOT NULL ORDER BY CHEGADA)

		IF (@ID = 1)
			BEGIN
				SET @FK_CLIENTE = (SELECT ID_CLIENTE FROM ##FILA WHERE IDFILA = @ID);
				INSERT INTO MESA(NUMERO,ENTRADA,ID_CLIENTE)
				SELECT @N_MESA,GETDATE(), @FK_CLIENTE;

				IF (SELECT COUNT(*) FROM MESA WHERE IDMESA = @@IDENTITY) > 0
					BEGIN
						PRINT 'O CLIENTE FOI DIRECIONADO PARA A MESA | ID >=1'
						SELECT TOP(1)* FROM VW_MESA ORDER BY ENTRADA DESC

						DELETE FROM ##FILA WHERE IDFILA = @ID;
					END
				ELSE
					BEGIN
						PRINT 'ERRO!'
					END
			END
		ELSE
			BEGIN
				INSERT INTO MESA(NUMERO,ENTRADA,ID_CLIENTE)
				SELECT @N_MESA,GETDATE(),NULL;

				IF(SELECT COUNT(*) FROM MESA WHERE IDMESA = @@IDENTITY) > 0
					BEGIN
						PRINT 'O CLIENTE FOI DIRECIONADO PARA A MESA | ID = 0'
						SELECT * FROM VW_MESA ORDER BY ENTRADA  DESC

						DELETE FROM ##FILA WHERE CHEGADA = (SELECT MIN(CHEGADA) FROM ##FILA);
					END

			END
	END
GO