-- Criando as tabelas sem relacionamento.

CREATE DATABASE RESTAURANTE
GO

USE RESTAURANTE
GO

CREATE TABLE FUNCIONARIOS
(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
	NOME_FUNCIONARIO VARCHAR(128) NOT NULL,
	CPF NVARCHAR(11) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	CARGO NVARCHAR(50),
	ATIVO BIT NOT NULL
)
GO

CREATE TABLE AGENDA
(
	IDAGENDA INT PRIMARY KEY IDENTITY,
	LUGARES INT NOT NULL,
	HORARIO DATETIME NOT NULL,
	TOLERANCIA AS DATEADD(MINUTE,15,HORARIO),
	CHEGADA DATETIME NULL
)
GO

CREATE TABLE CLIENTE
(
	IDCLIENTE INT PRIMARY KEY IDENTITY,
	NOME_CLIENTE VARCHAR(128) NOT NULL,
	CPF NVARCHAR(11) NULL
)
GO

CREATE TABLE CONTATOS
(
	IDCONTATO INT PRIMARY KEY IDENTITY,
	EMAIL NVARCHAR(128) NOT NULL,
	CELULAR NVARCHAR(11) NOT NULL,
	TELEFONE NVARCHAR(10) NULL
)
GO

CREATE TABLE MESA
(
	IDMESA INT PRIMARY KEY IDENTITY,
	NUMERO INT NOT NULL,
	ENTRADA DATETIME NOT NULL,
	SAIDA DATETIME NULL
)
GO

CREATE TABLE PEDIDOS 
(
	IDPEDIDO INT PRIMARY KEY IDENTITY,
	HORARIO DATETIME NOT NULL,
	OBS NVARCHAR(99) NULL,
	HORA_ENTREGA DATETIME NULL
) 
GO

CREATE TABLE CARDAPIO
(
	IDCARDAPIO INT PRIMARY KEY IDENTITY,
	NOME_PRATO NVARCHAR(50) NOT NULL,
	TIPO VARCHAR(30) NOT NULL
)
GO


