USE RESTAURANTE

CREATE TABLE ##FILA
(
	IDFILA INT PRIMARY KEY IDENTITY,
	CHEGADA DATETIME DEFAULT(GETDATE()),
	CHAMADA DATETIME NULL,
	CPF NVARCHAR(11) NULL,
	NOME NVARCHAR(128) NULL,
	ID_CLIENTE INT
	--ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE)
)
GO


CREATE TABLE ##LISTA
(
	IDLISTA INT PRIMARY KEY IDENTITY,
	ENTRADA DATETIME DEFAULT(GETDATE()),
	SAIDA DATETIME NULL,
	ID_PEDIDO INT
)
GO


