USE RESTAURANTE

CREATE TABLE ##FILA
(
	IDMESA INT PRIMARY KEY IDENTITY,
	CHEGADA DATETIME DEFAULT(GETDATE()),
	CHAMADA DATETIME NULL,
	CPF NVARCHAR(11) NULL,
	NOME NVARCHAR(128) NULL,
	ID_CLIENTE INT
	--ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE)
)
GO

DROP TABLE #FILA

CREATE TABLE #LISTA
(
	IDLISTA INT PRIMARY KEY,
	ENTRADA DATETIME DEFAULT(GETDATE()),
	SAIDA DATETIME NULL,
	--ID_PEDIDO INT FOREIGN KEY REFERENCES PEDIDOS(IDPEDIDO)
)
GO

SELECT * FROM #FILA

SP_HELP ##LISTA
GO

