
USE RESTAURANTE;
GO

CREATE VIEW VW_CLIENTES
AS
	SELECT CL.NOME_CLIENTE, CL.CPF, 
	CO.EMAIL, CO.CELULAR, ISNULL(CO.TELEFONE, 'VAZIO') AS TELEFONE 
	FROM CLIENTE AS CL
	INNER JOIN CONTATOS AS CO
	ON CL.IDCLIENTE = CO.ID_CLIENTE
GO


CREATE VIEW VW_AGENDAMENTO
AS
	SELECT CL.CPF,A.LUGARES,A.HORARIO, A.TOLERANCIA,A.CHEGADA, 
	F.NOME_FUNCIONARIO AS [ATENDIDO POR ],CL.NOME_CLIENTE AS [CLIENTE], 
	CO.CELULAR AS CONTATO, 
	( --COLUNA POSSUI VERIFICAÇÃO DE COMPARECIMENTO
		CASE WHEN A.TOLERANCIA > GETDATE() THEN
			(ISNULL(CONVERT(VARCHAR,A.CHEGADA), 'AGUARDANDO'))
		ELSE
			(ISNULL(CONVERT(VARCHAR,A.CHEGADA), 'NÃO COMPARECEU'))
		END
	) AS [STATUS]
	FROM CLIENTE AS CL
	INNER JOIN AGENDA AS A
	ON  A.ID_CLIENTE = CL.IDCLIENTE
	INNER JOIN FUNCIONARIOS AS F
	ON A.ID_FUNCIONARIO = F.IDFUNCIONARIO
	LEFT JOIN CONTATOS AS CO
	ON CO.ID_CLIENTE = CL.IDCLIENTE
GO

SELECT * FROM VW_AGENDAMENTO
drop view vw_agendamento
go


CREATE VIEW VW_MESA
AS
	SELECT M.NUMERO, M.ENTRADA, 
	ISNULL(CONVERT(VARCHAR,M.SAIDA), 'UTILIZANDO') AS SAÍDA, CL.NOME_CLIENTE AS CLIENTE
	FROM MESA AS M
	LEFT JOIN CLIENTE AS CL
	ON M.ID_CLIENTE = CL.IDCLIENTE
GO

DROP VIEW VW_MESA

SELECT * FROM VW_MESA
SELECT * FROM MESA
go


CREATE VIEW VW_PEDIDOS
AS
	SELECT P.HORARIO,C.NOME_PRATO,
	(ISNULL(P.OBS,'NENHUMA')) AS OBSERVAÇÃO,
	M.NUMERO AS MESA, F.NOME_FUNCIONARIO AS GARÇOM,
	(ISNULL(CONVERT(VARCHAR,P.HORA_ENTREGA),'AGUARDANDO')) AS [ENTREGUE?]
	FROM PEDIDOS AS P
	LEFT JOIN CARDAPIO AS C
	ON P.ID_CARDAPIO = C.IDCARDAPIO
	INNER JOIN MESA AS M
	ON P.ID_MESA = M.IDMESA
	INNER JOIN FUNCIONARIOS AS F
	ON P.ID_FUNCIONARIO = F.IDFUNCIONARIO;
GO

DROP VIEW VW_PEDIDOS

SELECT * FROM PEDIDOS

SELECT * FROM VW_CLIENTES GO
SELECT * FROM VW_AGENDAMENTO GO
SELECT * FROM VW_MESA GO
SELECT * FROM VW_PEDIDOS GO
